apiVersion: v1
kind: Service
metadata:
    name: "nas-7ff4"
    labels:
        app: "nas-7ff4"
spec:
    type: LoadBalancer
    ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: "nas-7ff4"