apiVersion: v1
kind: Service
metadata:
    name: "nastasia2-a0c2"
    labels:
        app: "nastasia2-a0c2"
spec:
    type: LoadBalancer
    ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: http
    selector:
        app: "nastasia2-a0c2"